version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-stretch

    working_directory: /go/src/github.com/ironstar-io/tokaido

    steps:
      - checkout     

      - run: dep ensure
      
      - run: make build-windows
      - run: make build-linux
      - run: make build-osx
      - run: ls dist/

      - store_artifacts:
          path: /go/src/github.com/ironstar-io/tokaido/dist/
          destination: artifacts

      - persist_to_workspace:        
          root: /go/src/github.com/ironstar-io/tokaido/
          paths: 
            - dist

  release-edge:
    docker:
      - image: circleci/golang:1.10-stretch
    environment:
      VERSION: edge
    steps:
      - attach_workspace:
          at: ./dist
      - run: go get github.com/tcnksm/ghr
      - run:
          name: "Publish Linux Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ironstar-io -r tokaido -c ${CIRCLE_SHA1} -prerelease -delete ${VERSION} ./dist/

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release-edge:
          requires: 
            - build
          filters:
            branches:
              only:               
                - build-system
      # - release-stable:
      #     requires: 
      #       - build
      #     filters:
      #       branches:
      #         only:               
      #           - master
      #       tags:
      #         only: /^v.*/
